### ISSUE TITLE
SVG Icon not working with Version 2.0.0

### ISSUE THREAD

**Issue by sirtheta** [MartinTopfstedt/FontAwesome6#11]
I updated to the latest stabel version today and encountered errors in mmy project. 
I am using the FontAwesome6.Svg package.

I do not know what I have to change that the new version is Working...
I am using the SVG nuGet like that:

`xmlns:fa6="http://schemas.fontawesome.com/icons/svg"`

and then in my button:
`    <Button>
      <Button.Content>
        <Grid>
          <Grid.RowDefinitions>
            <RowDefinition Height="80"/>
            <RowDefinition Height="0.5*"/>
          </Grid.RowDefinitions>
          <fa6:ImageAwesome Icon="Solid_Building" 
                            Height="80"
                            PrimaryColor="{Binding SomeBinding}"/>
          <TextBlock Text="Button Text" 
                     Grid.Row="1"/>
        </Grid>
      </Button.Content>
    </Button`

It was working perfectly fine but now I get an error in the `Icon` --> Value cannot be null (Parameter 'stream')
What is the soluton for this problem?

**Comment by MartinTopfstedt** [comment]
Hi, is this in wpf, uwp or winui?

**Comment by sirtheta** [comment]
Sorry, forogt to mention that. It is WPF.

**Comment by MartinTopfstedt** [comment]
Hi i fixed the bug, please try 2.0.1

**Comment by sirtheta** [comment]
Hi, tryed just now, still the same problem.
![grafik](https://user-images.githubusercontent.com/7117947/166543295-e5106535-a51f-4376-b3a6-f37cae50ebd3.png)
