### ISSUE TITLE
WPF Icons do not display unless fonts are in temp/. Fonts being in temp/6.1.2/ does not work.

### ISSUE THREAD

**Issue by EricEzaM** [MartinTopfstedt/FontAwesome6#33]
Fresh install - ensure there are NO font awesome fonts in your `%temp%` folder.

![image](https://user-images.githubusercontent.com/41730826/192949797-fbea3c3d-83f6-4c94-a118-cfb182381e19.png)

Run a project with a simple UI as above that uses some icons. The icons do not display:
![image](https://user-images.githubusercontent.com/41730826/192950046-20678a47-2d9b-4934-92e7-50455aebaaa4.png)

Now copy the fonts from `%temp%/6.1.2/` into `%temp%` (main temp folder). Re run the application and it works:
![image](https://user-images.githubusercontent.com/41730826/192950209-c8e9be42-8437-46a9-a06e-52ea59cb4136.png)

I tried to fix this myself, I though this was due to this change: https://github.com/MartinTopfstedt/FontAwesome6/commit/3d2d307dcbceeaae34983be906914e7661ccc58e

But I cannot seem to fix it. I changed the code so that the base URI for the font families is `%temp%/6.1.2/ ` rather than just `%temp%`, but it still only works when the font files are in `%temp%`. Not sure from where those files are being loaded.

Any help appreciated.

**Comment by MartinTopfstedt** [comment]
Hi, you are right, this is a bug, i fixed it an will provide v2.4.1 with a fix.

**Comment by EricEzaM** [comment]
Hmm, before I opened this issue I tries to fox the issue myself. I cloned the source and I made those _exact_ changes in your commit, but it still didn't work for me. It only loaded the fonts when they were in the temp folder. I have no idea why that was happening.

Did you test this and confirm the fix worked? If so that's great but I just couldn't get it working locally for me :(

**Comment by EricEzaM** [comment]
I can confirm this still does not fix the issue. The font family constructor gets passed a uri: `%temp%/6.1.2`. It appears that because there is not trailing `/`, it treats `6.1.2` as a _file_, not a _folder_ in which to find the fonts.

Changing `LoadAllStyles(path);` to `LoadAllStyles(path + Path.DirectorySeparatorChar);` fixes the issue for me.

**Comment by MartinTopfstedt** [comment]
Hi, you are completely right. I added your fix and will release a new bug fix. Sorry for not testing it earlier.
